version: "3.9"

services:
  api:
    build: .
    container_name: collab_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node src/server.js

  worker:
    build: .
    container_name: collab_worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node src/workers/job.worker.js

  postgres:
    image: postgres:15
    container_name: collab_postgres
    environment:
      POSTGRES_DB: collab-workspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654321
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: collab_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
